language: php

matrix:
  fast_finish: true
  include:
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1

before_install:
  - composer self-update
  - composer validate

install:
  # gearman
  - sudo apt-get remove gearman-job-server
  - sudo apt-get install gearman-job-server libgearman-dev
  - printf "\n"| pecl install gearman-1.0.3
  ## Composer
  - composer install

before_script:
  - gearmand -d

script:
  - vendor/bin/phpunit

